language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls


services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE testdb;'

env:
  - DB_NAME="testdb" DB_USER="root" DB_PASS="" DB_HOST="127.0.0.1" DB_PORT="3306"
  
  
# command to run tests
script:
  - pytest --cov=app

  
after_success:
  - coveralls